
output "ec2_public_ip" {
  value = aws_instance.app.public_ip
}

output "s3_bucket_name" {
  value = aws_s3_bucket.models_bucket.bucket
}

output "sqs_queue_url" {
  value = aws_sqs_queue.models_notifications.id
}

output "private_key_pem" {
  description = "Private key generated by Terraform"
  value       = tls_private_key.deployer.private_key_pem
  sensitive   = true
}

output "nlb_dns_name" {
  description = "NLB DNS name (for debugging)"
  value       = aws_lb.nlb.dns_name
}

output "api_invoke_url" {
  description = "Invoke URL for API Gateway (stage)"
  value       = "https://${aws_api_gateway_rest_api.rest_api.id}.execute-api.${var.region}.amazonaws.com/${aws_api_gateway_stage.prod.stage_name}"
}
